"""lamp plug

SPEC_lamp_switch.md §6 (D9) — the lamp plug this machine found last time and its password. App DB: the plug
belongs to this desk's network, not to the server. A new table, so no existing row can regress.

Revision ID: 63efd411276f
Revises: cb8c2942a6bc
Create Date: 2026-10-02 03:51:26.254191
"""
from alembic import op
import sqlalchemy as sa


revision = '63efd411276f'
down_revision = 'cb8c2942a6bc'
branch_labels = None
depends_on = None


def upgrade():
    # The table may already be there: DbBase.save_session()/session_factory() run create_all on every use, so any
    # code that touched this DB with the new model before the boot-time upgrade built it already (empty, same
    # schema). Then there is nothing to do but stamp.
    if 'lamp_plug' in sa.inspect(op.get_bind()).get_table_names():
        return
    op.create_table('lamp_plug',
    sa.Column('driverName', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('deviceId', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lamp_plug')
    # ### end Alembic commands ###
