"""baseline app schema

Revision ID: 7200faf1d770
Revises: 
Create Date: 2026-07-18 02:34:43.956229
"""
from alembic import op
import sqlalchemy as sa


revision = '7200faf1d770'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_config_to_spectrometer_profile',
    sa.Column('isDefault', sa.Boolean(), nullable=True),
    sa.Column('application_config_id', sa.String(), nullable=False),
    sa.Column('spectrometer_profile_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_config_id'], ['application_config.id'], ),
    sa.PrimaryKeyConstraint('application_config_id', 'spectrometer_profile_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_config_to_spectrometer_profile')
    op.drop_table('application_config')
    # ### end Alembic commands ###
