"""monitor record on the spectral workflow

SPEC_settled_measurement.md §15.2 — ONE nullable TEXT column holding the plugin's SELF-DESCRIBING
settling record (columns + rows + answer + policy + evaluator version). NULL for every plain-burst
capture, which is most of them, so no data is touched and the downgrade is a clean drop.
⛔ Deliberately NOT a table of typed metric columns: that would put one plugin's physics in the schema.

Revision ID: 84fe759ba6d7
Revises: f0ac79b33dde
Create Date: 2026-08-17 02:52:16.145667
"""
from alembic import op
import sqlalchemy as sa


revision = '84fe759ba6d7'
down_revision = 'f0ac79b33dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spectral_workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitorRecordJson', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spectral_workflow', schema=None) as batch_op:
        batch_op.drop_column('monitorRecordJson')

    # ### end Alembic commands ###
