"""D4 sectionedPhases on spectral_workflow

SPEC_settled_measurement.md §27.14a — which phases are sectioned by step ("Reference" / "Sample" instead of
one "Acquisition"). The plugin declares it, the workflow carries it, and the chevron, a re-opened run, the
PDF and a LIMS addon all read it from the record instead of from a live plugin.

⚠ A workflow-level FACT needs a real column; a view-model field would have ridden the resultJson blob
(§27.14/W3 vs §27.16/N5). NULL on every existing row -> no sub-sections -> exactly the pre-D4 behaviour, so
archived runs cannot regress.

Revision ID: cb8c2942a6bc
Revises: dccf62fc4d10
Create Date: 2026-08-17 20:27:30.354804
"""
from alembic import op
import sqlalchemy as sa


revision = 'cb8c2942a6bc'
down_revision = 'dccf62fc4d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spectral_workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sectionedPhasesJson', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spectral_workflow', schema=None) as batch_op:
        batch_op.drop_column('sectionedPhasesJson')

    # ### end Alembic commands ###
