"""drop reportOnly - the settling views belong to the sample step

SPEC_settled_measurement.md §27.12 — reverts ed08faaf1864 one session later, on purpose.

`reportOnly` was invented to keep a settling step in PROCESSING out of the UI while the report still
collected it. ⛔ It solved a problem created by putting the views on the wrong step: they are provenance
of the SAMPLE capture, so they belong on that step's EvaluationResult — which the report already
harvests and which no host renders for a CaptureView step. One construction, one home, no flag.
⚠ Nothing is lost: the column was never written outside a dev database.

Revision ID: dccf62fc4d10
Revises: ed08faaf1864
Create Date: 2026-08-17 04:53:20.199839
"""
from alembic import op
import sqlalchemy as sa


revision = 'dccf62fc4d10'
down_revision = 'ed08faaf1864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spectral_workflow_step', schema=None) as batch_op:
        batch_op.drop_column('reportOnly')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spectral_workflow_step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reportOnly', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
