"""report-only steps

Revision ID: ed08faaf1864
Revises: 84fe759ba6d7
Create Date: 2026-08-17 04:38:28.154044
"""
from alembic import op
import sqlalchemy as sa


revision = 'ed08faaf1864'
down_revision = '84fe759ba6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spectral_workflow_step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reportOnly', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spectral_workflow_step', schema=None) as batch_op:
        batch_op.drop_column('reportOnly')

    # ### end Alembic commands ###
