"""plugin identity (codeRef,version) + sealed columns (B0/B1)

Revision ID: 405d2ce2cec1
Revises: f641f17a1539
Create Date: 2026-07-18 02:43:31.658226
"""
from alembic import op
import sqlalchemy as sa


revision = '405d2ce2cec1'
down_revision = 'f641f17a1539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_plugin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('keyId', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('targetSdkVersion', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_db_plugin_coderef_version', ['codeRef', 'version'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_plugin', schema=None) as batch_op:
        batch_op.drop_constraint('uq_db_plugin_coderef_version', type_='unique')
        batch_op.drop_column('targetSdkVersion')
        batch_op.drop_column('author')
        batch_op.drop_column('keyId')
        batch_op.drop_column('signature')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
