"""baseline server schema

Revision ID: f641f17a1539
Revises: 
Create Date: 2026-07-18 02:34:32.023633
"""
from alembic import op
import sqlalchemy as sa


revision = 'f641f17a1539'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('passwordHash', sa.String(), nullable=True),
    sa.Column('displayName', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('registeredSerial', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('app_user_role',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('db_plugin',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('codeRef', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('pdfRef', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectral_line_master_data',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('colorName', sa.String(), nullable=True),
    sa.Column('mainColorName', sa.String(), nullable=True),
    sa.Column('nanometer', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectrometer_calibration_profile',
    sa.Column('regionOfInterestX1', sa.Integer(), nullable=True),
    sa.Column('regionOfInterestY1', sa.Integer(), nullable=True),
    sa.Column('regionOfInterestX2', sa.Integer(), nullable=True),
    sa.Column('regionOfInterestY2', sa.Integer(), nullable=True),
    sa.Column('interpolationCoefficientA', sa.Float(), nullable=True),
    sa.Column('interpolationCoefficientB', sa.Float(), nullable=True),
    sa.Column('interpolationCoefficientC', sa.Float(), nullable=True),
    sa.Column('interpolationCoefficientD', sa.Float(), nullable=True),
    sa.Column('calibrationSpectrumJson', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectrometer_sensor_chip',
    sa.Column('vendorName', sa.String(), nullable=True),
    sa.Column('productName', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectrometer_style',
    sa.Column('styleId', sa.String(), nullable=True),
    sa.Column('styleName', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectrometer_vendor',
    sa.Column('vendorName', sa.String(), nullable=True),
    sa.Column('vendorId', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user_to_app_user_role',
    sa.Column('app_user_id', sa.String(), nullable=False),
    sa.Column('app_user_role_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['app_user_role_id'], ['app_user_role.id'], ),
    sa.PrimaryKeyConstraint('app_user_id', 'app_user_role_id', 'id')
    )
    op.create_table('spectral_line',
    sa.Column('pixelIndex', sa.Integer(), nullable=True),
    sa.Column('spectrometerCalibrationProfile_id', sa.String(), nullable=True),
    sa.Column('spectralLineMasterDataId', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['spectralLineMasterDataId'], ['spectral_line_master_data.id'], ),
    sa.ForeignKeyConstraint(['spectrometerCalibrationProfile_id'], ['spectrometer_calibration_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectrometer_sensor',
    sa.Column('vendorId', sa.String(), nullable=True),
    sa.Column('vendorName', sa.String(), nullable=True),
    sa.Column('sellerName', sa.String(), nullable=True),
    sa.Column('modelId', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('codeName', sa.String(), nullable=True),
    sa.Column('isVirtual', sa.Boolean(), nullable=True),
    sa.Column('spectrometerSensorChipId', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['spectrometerSensorChipId'], ['spectrometer_sensor_chip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('appUserId', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('providerOrderId', sa.String(), nullable=True),
    sa.Column('providerCaptureId', sa.String(), nullable=True),
    sa.Column('amountMinor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['appUserId'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectrometer',
    sa.Column('modelName', sa.String(), nullable=True),
    sa.Column('spectrometerSensorId', sa.String(), nullable=True),
    sa.Column('spectrometerVendorId', sa.String(), nullable=True),
    sa.Column('spectrometerStyleId', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['spectrometerSensorId'], ['spectrometer_sensor.id'], ),
    sa.ForeignKeyConstraint(['spectrometerStyleId'], ['spectrometer_style.id'], ),
    sa.ForeignKeyConstraint(['spectrometerVendorId'], ['spectrometer_vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectrometer_profile',
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('spectrometerId', sa.String(), nullable=True),
    sa.Column('spectrometerCalibrationProfileId', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['spectrometerCalibrationProfileId'], ['spectrometer_calibration_profile.id'], ),
    sa.ForeignKeyConstraint(['spectrometerId'], ['spectrometer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spectrometer_setup',
    sa.Column('spectrometerProfileId', sa.String(), nullable=True),
    sa.Column('pluginId', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pluginId'], ['db_plugin.id'], ),
    sa.ForeignKeyConstraint(['spectrometerProfileId'], ['spectrometer_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spectrometer_setup')
    op.drop_table('spectrometer_profile')
    op.drop_table('spectrometer')
    op.drop_table('transaction')
    op.drop_table('spectrometer_sensor')
    op.drop_table('spectral_line')
    op.drop_table('app_user_to_app_user_role')
    op.drop_table('spectrometer_vendor')
    op.drop_table('spectrometer_style')
    op.drop_table('spectrometer_sensor_chip')
    op.drop_table('spectrometer_calibration_profile')
    op.drop_table('spectral_line_master_data')
    op.drop_table('db_plugin')
    op.drop_table('app_user_role')
    op.drop_table('app_user')
    # ### end Alembic commands ###
