from enum import Enum

class SpectralLineMasterDataColorName(str, Enum):
    # 'MercuryFrenchViolet'
    # 'MercuryBlue'
    # 'TerbiumAqua'
    # 'MercuryMangoGreen'
    # 'EuropiumMiddleYellow'
    # 'EuropiumCyberYellow'
    # 'EuropiumAmber'
    # 'EuropiumVividGamboge'
    # 'EuropiumInternationalOrange'
    # 'EuropiumRed'

    MERCURY_FRENCH_VIOLET='MERCURY_FRENCH_VIOLET'
    MERCURY_BLUE='MERCURY_BLUE'
    TERBIUM_AQUA='TERBIUM_AQUA'
    MERCURY_MANGO_GREEN_LEFT='MERCURY_MANGO_GREEN_LEFT'
    MERCURY_MANGO_GREEN = 'MERCURY_MANGO_GREEN'
    EUROPIUM_MIDDLE_YELLOW='EUROPIUM_MIDDLE_YELLOW'
    EUROPIUM_CYBER_YELLOW='EUROPIUM_CYBER_YELLOW'
    EUROPIUM_AMBER='EUROPIUM_AMBER'
    EUROPIUM_VIVID_GAMBOGE='EUROPIUM_VIVID_GAMBOGE'
    EUROPIUM_INTERNATIONAL_ORANGE='EUROPIUM_INTERNATIONAL_ORANGE'
    EUROPIUM_RED='EUROPIUM_RED'

    EUROPIUM_RED_FAR_660 = 'EUROPIUM_RED_FAR_660'

    EUROPIUM_RED_FAR_680 = 'EUROPIUM_RED_FAR_680'

    EUROPIUM_RED_FAR_690 = 'EUROPIUM_RED_FAR_690'

    EUROPIUM_RED_FAR_700 = 'EUROPIUM_RED_FAR_700'

    EUROPIUM_RED_FAR_710 = 'EUROPIUM_RED_FAR_710'

    ARGON_RED_FAR_760 = 'ARGON_RED_FAR_760'

    ARGON_RED_FAR_810 = 'ARGON_RED_FAR_810'

    MERCURY_OR_TERBIUM_LEMON_GLACIER = 'MERCURY_OR_TERBIUM_LEMON_GLACIER'

    MERCURY_OR_TERBIUM_YELLOW = 'MERCURY_OR_TERBIUM_YELLOW'

    TERBIUM_OR_EUROPIUM_YELLOW_ROSE = 'TERBIUM_OR_EUROPIUM_YELLOW_ROSE'

    TERBIUM_VIVID_ORANGE = 'TERBIUM_VIVID_ORANGE'



